### ISSUE TITLE
how can i get the 'text' of a syntax node

### ISSUE THREAD

**Issue by hollowdjj** [bonede/tree-sitter-ng#19]
how can i get the 'text' of a syntax node? For example, when i have got a syntax node which representing a method, how can i get the text of this method? 
In tree-sitter-python, i can achieve this by just calling `node.text.decode('utf-8')`. How can i do the same thing is this binding?

**Comment by bonede** [comment]
Hi @hollowdjj 

There are no Python equivalent for now.

The best solution i can think of is

```java

byte[] bytes = src.getBytes(StandardCharsets.UTF_8);
int startByte = node.getStartByte();
int endByte = node.getEndByte();
byte[] nodeBytes = Arrays.copyOfRange(bytes, startByte, endByte);
String text = new String(nodeBytes, StandardCharsets.UTF_8);

```

**Comment by hollowdjj** [comment]
This works pretty good, thx for responding~

**Comment by cxx199921110** [comment]
emm,no getText() api,hope to update
