### ISSUE TITLE
Build fails with incompatible types on 0.22.6

### ISSUE THREAD

**Issue by brookite** [bonede/tree-sitter-ng#24]
I recently upgraded to version 0.22.6 from 0.22.5 and noticed that my project stopped building. It gives this build error щт 0.22.6. But on 0.22.5 project builds successfully.

Build error:
```
java: incompatible types: org.treesitter.TreeSitterPython cannot be converted to org.treesitter.TSLanguage
```

Code fragments:
```java
import org.treesitter.TreeSitterPython;
import org.treesitter.TSLanguage;
import org.treesitter.TSNode;
import org.treesitter.TSTree;
import org.treesitter.TSParser;
// ...
TSParser parser = new TSParser();
TSLanguage pyLanguage = new TreeSitterPython();
parser.setLanguage(pyLanguage);
// ...
```

Can you tell me if this is a bug, will it be fixed? Or what do I need to do?

**Comment by bonede** [comment]
Please upgrade python parser to v0.21.0a. It should fix the issue.
