### ISSUE TITLE
Periodic Crashes in Production Environment

### ISSUE THREAD

**Issue by csophys** [bonede/tree-sitter-ng#25]
I am using TreeSitter in a production environment. However, during actual use, periodic crashes occur. Each crash file is about 5GB, I hope to find the cause and thoroughly resolve this issue. Currently, I have not pinpointed the specific request logs that lead to the crashes.

Could you please help me understand how to resolve this problem? Or what can I do to provide more information to help identify the issue?

![image](https://github.com/bonede/tree-sitter-ng/assets/1715431/c27ab65c-1220-4dfc-a6a3-b2cf65850907)

**Comment by csophys** [comment]
Here are two additional scenarios where clashes occur:

Coredump occurring during the Cleaner process.
![image](https://github.com/bonede/tree-sitter-ng/assets/1715431/a762f4da-5396-46d5-a56d-18458232caf0)


Coredump occurring when accessing the child of a node.
![image](https://github.com/bonede/tree-sitter-ng/assets/1715431/285f3b14-e261-4797-9f02-da5afed65a10)

**Comment by bonede** [comment]
Could you share the source code and code snippets that crashed the program?

**Comment by jingyuan4ever** [comment]
Here is my code
```
    private static String tryRecoverFromTheError(Language language, String before, String after, String firstLine) {
        // try to recover from error
        List<TSNode> errorNodes = null;
        try {
            TSTree cst = TreeSitterUtilsByLanguage.parse(language, before + firstLine + after);
            TSTreeCursor unit = getUnit(language, cst, before.getBytes(StandardCharsets.UTF_8).length);
            TSTreeCursor cursor = new TSTreeCursor(unit.currentNode());
            errorNodes = new ArrayList<>();
            List<TSNode> missingNodes = new ArrayList<>();
            boolean loop = true;
            while (loop) {
                if (cursor.currentNode().hasError()) {
                    if (cursor.currentNode().isMissing()) {
                        missingNodes.add(cursor.currentNode());
                    } else {
                        errorNodes.add(cursor.currentNode());
                    }
                }
                if (cursor.gotoFirstChild() || cursor.gotoNextSibling()) {
                    continue;
                }
                do {
                    if (!cursor.gotoParent() || cursor.currentNode().equals(unit.currentNode())) {
                        loop = false;
                        break;
                    }
                } while (!cursor.gotoNextSibling());
            }
            for (TSNode missing : missingNodes) {
                List<TSNode> notRecovered = new ArrayList<>();
                for (TSNode error : errorNodes) {
                    if (!(error.getStartByte() <= missing.getStartByte() && error.getEndByte() >= missing.getEndByte() && error.getStartByte() != missing.getStartByte())) {
                        notRecovered.add(error);
                    }
                }
                errorNodes = notRecovered;
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        if (errorNodes.isEmpty()) {
            return firstLine;
        } else {
            return "";
        }
    }

**Comment by csophys** [comment]
> Could you share the source code and code snippets that crashed the program?

the code is similar as [jingyuan4ever](https://github.com/jingyuan4ever) ，here is the code create the Tree
![image](https://github.com/bonede/tree-sitter-ng/assets/1715431/04c2e609-b159-4055-b4d0-1d93fbe9999e)

**Comment by bonede** [comment]
`v0.22.6a` has fixed a few memory related issues, please upgrade to this version and try again.

If it still occurs, please paste the test code here.

**Comment by csophys** [comment]
> `v0.22.6a` has fixed a few memory related issues, please upgrade to this version and try again.
> 
> If it still occurs, please paste the test code here.

ok，thanks. we upgrade to this version and try again
