### ISSUE TITLE
How can i get the 'name' of a matched syntax node?

### ISSUE THREAD

**Issue by anooakv** [bonede/tree-sitter-ng#30]
I am running following query on syntax tree.
`(method_declaration
 name: (identifier) @name) @target`

How can i get the 'name' of a syntax node? For example, when i have got a syntax node which representing a method_declaration, how can i get the name of this method_declaration node?
In web-tree-sitter, i can achieve this by just calling capture.name.
 How can i do the same thing is this binding?

**Comment by aaswan** [comment]
In the following query
`TreeSitterQuery query = new TSQuery(json, "((document) @root)");`
https://github.com/bonede/tree-sitter-ng#:~:text=query%20%3D%20new-,TSQuery,-(json%2C

How can I find the capture with the name 'root' inside the for loop

```
while (cursor.nextMatch(match)) {
      TSQueryCapture[] captures = match.getCaptures();
      for (TSQueryCapture capture : captures) {
         // How can i find the capture with the name "root", that is specified in the TSQuery @root
      }
}
```

**Comment by bonede** [comment]
Hi there, 

There is no equivalent  to “search for capture by the tag”, 
but you can archive by using TSCursor#getCaptures() to iterate over the captures.

Example code: https://github.com/bonede/tree-sitter-ng/blob/e4c9c3dd3c5fabcc5bf845b1dcffbf2b47681936/tree-sitter/src/test/java/org/treesitter/TSQueryCursorTest.java#L101
