### ISSUE TITLE
TreeSitterSql randomly produces null pointers

### ISSUE THREAD

**Issue by valepakh** [bonede/tree-sitter-ng#32]
This test sometimes fails:
```java
@RepeatedTest(1000)
void nodeType() {
    TSParser parser = new TSParser();
    parser.setLanguage(new TreeSitterSql());
    TSTree tree = parser.parseString(null, "c");
    TSTreeCursor cursor = new TSTreeCursor(tree.getRootNode());
    TSNode node = cursor.currentNode();
    assertThat(node.getType(), is(notNullValue()));
}
```
It's unclear whether this method can return null or not but it seems to be dependent on the moon phase or something.
First repetition seems to reliably fail, then about 200 repetitions pass, then a dozen or so fail.
Most probably it's a tree-sitter-sql issue, but it's hard to tell without building the native code and debugging it.

**Comment by bonede** [comment]
`v0.22.6a` has fixed a few memory related issues, please upgrade to this version and try again.
