### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION when invoke ts_node_end_byte

### ISSUE THREAD

**Issue by fuhailong1998** [bonede/tree-sitter-ng#33]
Here are logs:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffcadefea40, pid=39800, tid=15144
#
# JRE version: OpenJDK Runtime Environment JBR-17.0.10+1-1087.23-jcef (17.0.10+1) (build 17.0.10+1-b1087.23)
# Java VM: OpenJDK 64-Bit Server VM JBR-17.0.10+1-1087.23-jcef (17.0.10+1-b1087.23, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ffcadefea40
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://youtrack.jetbrains.com/issues/JBR
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Daether.connector.resumeDownloads=false -Didea.auto.reload.plugins=true -Didea.classpath.index.enabled=false -Didea.config.path=F:\ts\RubikStudio_new\AndroidStudio\build\idea-sandbox\config -Didea.is.internal=true -Didea.log.path=F:\ts\RubikStudio_new\AndroidStudio\build\idea-sandbox\system\log -Didea.paths.selector=IdeaIC2023.3 -Didea.platform.prefix=Idea -Didea.plugin.in.sandbox.mode=true -Didea.plugins.path=F:\ts\RubikStudio_new\AndroidStudio\build\idea-sandbox\plugins -Didea.required.plugins.id=com.ts.rubik.studio -Didea.system.path=F:\ts\RubikStudio_new\AndroidStudio\build\idea-sandbox\system -Didea.vendor.name=JetBrains -Dintellij.platform.runtime.repository.path=C:\Users\14143\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2023.3.6\570b1ee19744f941431cf270d989a88c111ec603\ideaIC-2023.3.6/modules/module-descriptors.jar -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader -Djbr.catch.SIGABRT=true -Djdk.attach.allowAttachSelf=true -Djdk.http.auth.tunneling.disabledSchemes= -Djdk.module.illegalAccess.silent=true -Djna.boot.library.path=C:\Users\14143\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2023.3.6\570b1ee19744f941431cf270d989a88c111ec603\ideaIC-2023.3.6/lib/jna/amd64 -Djna.noclasspath=true -Djna.nosys=true -Dkotlinx.coroutines.debug=off -Dpty4j.preferred.native.folder=C:\Users\14143\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2023.3.6\570b1ee19744f941431cf270d989a88c111ec603\ideaIC-2023.3.6/lib/pty4j -Dsplash=true -Dsun.io.useCanonCaches=false -Dsun.java2d.metal=true -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:CICompilerCount=2 -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+IgnoreUnrecognizedVMOptions -XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/jdk.internal.vm=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.fs=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.desktop/java.awt.dnd.peer=ALL-UNNAMED --add-opens=java.desktop/java.awt.event=ALL-UNNAMED --add-opens=java.desktop/java.awt.image=ALL-UNNAMED --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED --add-opens=java.desktop/sun.awt.datatransfer=ALL-UNNAMED --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED --add-opens=java.desktop/sun.awt.windows=ALL-UNNAMED --add-opens=java.desktop/sun.awt=ALL-UNNAMED --add-opens=java.desktop/sun.font=ALL-UNNAMED --add-opens=java.desktop/sun.java2d=ALL-UNNAMED --add-opens=java.desktop/sun.swing=ALL-UNNAMED --add-opens=java.desktop/com.sun.java.swing=ALL-UNNAMED --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED -Xms128m -Xmx2048m -Dfile.encoding=GBK -Duser.country=CN -Duser.language=zh -Duser.variant -ea com.intellij.idea.Main

Host: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz, 16 cores, 31G,  Windows 11 , 64 bit Build 22621 (10.0.22621.3527)
Time: Sat Jun 29 15:03:31 2024  Windows 11 , 64 bit Build 22621 (10.0.22621.3527) elapsed time: 44.408319 seconds (0d 0h 0m 44s)

---------------  T H R E A D  ---------------

Current thread (0x000002cf2e832110):  JavaThread "ApplicationImpl pooled thread 5" [_thread_in_native, id=15144, stack(0x000000f1ba200000,0x000000f1ba300000)]

Stack: [0x000000f1ba200000,0x000000f1ba300000],  sp=0x000000f1ba2fe270,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007ffcadefea40

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 20513  org.treesitter.TSParser.ts_node_end_byte(Lorg/treesitter/TSNode;)I (0 bytes) @ 0x000002ceaa5e1ff2 [0x000002ceaa5e1fa0+0x0000000000000052]
J 31370 c1 com.ts.rubik.studio.treesitter.ParseCodeUtil.getSlices(Lorg/treesitter/TSNode;Ljava/lang/String;Ljava/lang/String;I)Ljava/util/ArrayList; (323 bytes) @ 0x000002ce9c5d832c [0x000002ce9c5d7d20+0x000000000000060c]
J 31534 c1 com.ts.rubik.studio.treesitter.ParseCodeUtil.parseCodeIns(Lcom/intellij/openapi/vfs/VirtualFile;Lcom/intellij/openapi/fileEditor/TextEditor;Lcom/intellij/psi/PsiManager;I)Lcom/ts/rubik/studio/treesitter/data/OffsetDataResult; (1853 bytes) @ 0x000002ce9c666b1c [0x000002ce9c665600+0x000000000000151c]
j  com.ts.rubik.studio.treesitter.ParseCodeUtil.parseCodeFiles(Lcom/intellij/openapi/project/Project;Ljava/lang/String;Lcom/intellij/openapi/fileEditor/TextEditor;)Lcom/ts/rubik/studio/treesitter/data/OffsetDataResult;+328
j  com.ts.rubik.studio.editor.RubikEditorManagerImpl.calculateOtherFunctionAndClassDefinitions$lambda$15$lambda$14$lambda$13(Lcom/ts/rubik/studio/network/EditorRequest;Lcom/intellij/openapi/vfs/VirtualFile;Lcom/intellij/openapi/fileEditor/FileEditor;Lcom/intellij/openapi/vfs/VirtualFile;)V+52
j  com.ts.rubik.studio.editor.RubikEditorManagerImpl$$Lambda$4002+0x0000000101b81bb0.run()V+16
j  com.intellij.openapi.application.impl.ApplicationImpl$2.run()V+15
J 19507 c2 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; java.base@17.0.10 (14 bytes) @ 0x000002ceaa5ca548 [0x000002ceaa5ca500+0x0000000000000048]
J 25291 c1 com.intellij.util.concurrency.ContextCallable.call()Ljava/lang/Object; (60 bytes) @ 0x000002ce9a6604fc [0x000002ce9a660460+0x000000000000009c]
J 29511 c2 java.util.concurrent.FutureTask.run()V java.base@17.0.10 (123 bytes) @ 0x000002ceaa962a08 [0x000002ceaa962940+0x00000000000000c8]
J 22447 c1 com.intellij.util.concurrency.ContextRunnable.run()V (61 bytes) @ 0x000002ce9bbbda7c [0x000002ce9bbbd9e0+0x000000000000009c]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+92 java.base@17.0.10
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@17.0.10
j  java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run()Ljava/lang/Void;+23 java.base@17.0.10
j  java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run()Ljava/lang/Object;+1 java.base@17.0.10
J 10364 c1 java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; java.base@17.0.10 (17 bytes) @ 0x000002ce9aaf85cc [0x000002ce9aaf8540+0x000000000000008c]
j  java.util.concurrent.Executors$PrivilegedThreadFactory$1.run()V+15 java.base@17.0.10
j  java.lang.Thread.run()V+11 java.base@17.0.10
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x000002cf45a01d30
```

**Comment by fuhailong1998** [comment]
And the latest crash log:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe1b50ef10, pid=29252, tid=31408
#
# JRE version: OpenJDK Runtime Environment JBR-17.0.10+8-1207.12-jcef (17.0.10+8) (build 17.0.10+8-b1207.12)
# Java VM: OpenJDK 64-Bit Server VM JBR-17.0.10+8-1207.12-jcef (17.0.10+8-b1207.12, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [x86_64-windows-tree-sitter.dll+0xef10]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://youtrack.jetbrains.com/issues/JBR
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: exit -XX:ErrorFile=C:\Users\ts\\java_error_in_idea64_%p.log -XX:HeapDumpPath=C:\Users\ts\\java_error_in_idea64.hprof -Xms128m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+IgnoreUnrecognizedVMOptions -ea -Dsun.io.useCanonCaches=false -Dsun.java2d.metal=true -Djbr.catch.SIGABRT=true -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.attach.allowAttachSelf=true -Djdk.module.illegalAccess.silent=true -Dkotlinx.coroutines.debug=off -XX:CICompilerCount=2 -XX:ReservedCodeCacheSize=512m -XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend -XX:SoftRefLRUPolicyMSPerMB=50 -Dide.show.tips.on.startup.default.value=false -Xmx2048m -Dide.managed.by.toolbox=C:\Users\ts\AppData\Local\JetBrains\Toolbox\bin\jetbrains-toolbox.exe -Dtoolbox.notification.token=5bc04560-6608-4b19-b579-79924295c2c2 -Dtoolbox.notification.portFile=C:\Users\ts\AppData\Local\JetBrains\Toolbox\cache\ports\347193452.port -Djb.vmOptionsFile=C:\Users\ts\AppData\Roaming\\JetBrains\\IdeaIC2024.1\idea64.exe.vmoptions -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader -Didea.vendor.name=JetBrains -Didea.paths.selector=IdeaIC2024.1 -Djna.boot.library.path=D:\Tools\IntelliJ IDEA Community Edition 2024.1/lib/jna/amd64 -Dpty4j.preferred.native.folder=D:\Tools\IntelliJ IDEA Community Edition 2024.1/lib/pty4j -Djna.nosys=true -Djna.noclasspath=true -Dintellij.platform.runtime.repository.path=D:\Tools\IntelliJ IDEA Community Edition 2024.1/modules/module-descriptors.jar -Didea.platform.prefix=Idea -Dsplash=true -Daether.connector.resumeDownloads=false --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/jdk.internal.vm=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.fs=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.desktop/java.awt.dnd.peer=ALL-UNNAMED --add-opens=java.desktop/java.awt.event=ALL-UNNAMED --add-opens=java.desktop/java.awt.image=ALL-UNNAMED --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens=java.desktop/javax.swing.text=ALL-UNNAMED --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED --add-opens=java.desktop/sun.awt.datatransfer=ALL-UNNAMED --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED --add-opens=java.desktop/sun.awt.windows=ALL-UNNAMED --add-opens=java.desktop/sun.awt=ALL-UNNAMED --add-opens=java.desktop/sun.font=ALL-UNNAMED --add-opens=java.desktop/sun.java2d=ALL-UNNAMED --add-opens=java.desktop/sun.swing=ALL-UNNAMED --add-opens=java.desktop/com.sun.java.swing=ALL-UNNAMED --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED -Dide.native.launcher=true -Djcef.sandbox.ptr=000001E5EB9FE690 -Djcef.sandbox.cefVersion=122.1.9+gd14e051+chromium-122.0.6261.94 

Host: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz, 16 cores, 15G,  Windows 11 , 64 bit Build 22621 (10.0.22621.3672)
Time: Mon Jul  1 10:13:26 2024  Windows 11 , 64 bit Build 22621 (10.0.22621.3672) elapsed time: 710.017724 seconds (0d 0h 11m 50s)

---------------  T H R E A D  ---------------

Current thread (0x000001e63e8a7ff0):  JavaThread "ApplicationImpl pooled thread 19" [_thread_in_native, id=31408, stack(0x000000335a000000,0x000000335a100000)]

Stack: [0x000000335a000000,0x000000335a100000],  sp=0x000000335a0fe260,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [x86_64-windows-tree-sitter.dll+0xef10]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 20663  org.treesitter.TSParser.ts_node_type(Lorg/treesitter/TSNode;)Ljava/lang/String; (0 bytes) @ 0x000001e5906e8772 [0x000001e5906e8720+0x0000000000000052]
J 41726 c2 com.ts.rubik.studio.treesitter.b.a(Lorg/treesitter/TSNode;Lorg/a/a/a;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Lkotlin/collections/ArrayDeque;Lkotlin/collections/ArrayDeque;)V (1108 bytes) @ 0x000001e5914e6f2c [0x000001e5914e68a0+0x000000000000068c]
J 41726 c2 com.ts.rubik.studio.treesitter.b.a(Lorg/treesitter/TSNode;Lorg/a/a/a;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Lkotlin/collections/ArrayDeque;Lkotlin/collections/ArrayDeque;)V (1108 bytes) @ 0x000001e5914e7790 [0x000001e5914e68a0+0x0000000000000ef0]
J 41726 c2 com.ts.rubik.studio.treesitter.b.a(Lorg/treesitter/TSNode;Lorg/a/a/a;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Lkotlin/collections/ArrayDeque;Lkotlin/collections/ArrayDeque;)V (1108 bytes) @ 0x000001e5914e7790 [0x000001e5914e68a0+0x0000000000000ef0]
J 41726 c2 com.ts.rubik.studio.treesitter.b.a(Lorg/treesitter/TSNode;Lorg/a/a/a;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Lkotlin/collections/ArrayDeque;Lkotlin/collections/ArrayDeque;)V (1108 bytes) @ 0x000001e5914e7790 [0x000001e5914e68a0+0x0000000000000ef0]
J 41726 c2 com.ts.rubik.studio.treesitter.b.a(Lorg/treesitter/TSNode;Lorg/a/a/a;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Lkotlin/collections/ArrayDeque;Lkotlin/collections/ArrayDeque;)V (1108 bytes) @ 0x000001e5914e7790 [0x000001e5914e68a0+0x0000000000000ef0]
J 53447 c1 com.ts.rubik.studio.treesitter.b.a(Lcom/intellij/openapi/vfs/VirtualFile;Lcom/intellij/openapi/fileEditor/TextEditor;Lcom/intellij/psi/PsiManager;I)Lcom/ts/rubik/studio/treesitter/data/OffsetDataResult; (1840 bytes) @ 0x000001e5848fa6ac [0x000001e5848f6060+0x000000000000464c]
j  com.ts.rubik.studio.treesitter.b.a(Lcom/intellij/openapi/project/Project;Ljava/lang/String;Lcom/intellij/openapi/fileEditor/TextEditor;)Lcom/ts/rubik/studio/treesitter/data/OffsetDataResult;+321
j  com.ts.rubik.studio.editor.RubikEditorManagerImpl.calculateOtherFunctionAndClassDefinitions$lambda$12(Lcom/ts/rubik/studio/network/EditorRequest;Ljava/lang/String;Lcom/intellij/openapi/fileEditor/FileEditor;Lcom/intellij/openapi/vfs/VirtualFile;)V+38
j  com.ts.rubik.studio.editor.RubikEditorManagerImpl$$Lambda$4009+0x0000000101c2b818.run()V+16
j  com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run()V+18
J 23424 c2 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; java.base@17.0.10 (14 bytes) @ 0x000001e5907780c8 [0x000001e590778080+0x0000000000000048]
J 40567 c1 com.intellij.util.concurrency.ContextCallable.call()Ljava/lang/Object; (60 bytes) @ 0x000001e581c8258c [0x000001e581c82400+0x000000000000018c]
J 44633 c2 java.util.concurrent.FutureTask.run()V java.base@17.0.10 (123 bytes) @ 0x000001e5917b1cb0 [0x000001e5917b1a40+0x0000000000000270]
J 29192 c1 com.intellij.util.concurrency.ContextRunnable.run()V (61 bytes) @ 0x000001e58258310c [0x000001e582582f80+0x000000000000018c]
J 46065 c1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V java.base@17.0.10 (187 bytes) @ 0x000001e5800c130c [0x000001e5800c0a20+0x00000000000008ec]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@17.0.10
j  java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run()Ljava/lang/Void;+23 java.base@17.0.10
j  java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run()Ljava/lang/Object;+1 java.base@17.0.10
J 10333 c1 java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; java.base@17.0.10 (17 bytes) @ 0x000001e580c5594c [0x000001e580c558c0+0x000000000000008c]
j  java.util.concurrent.Executors$PrivilegedThreadFactory$1.run()V+15 java.base@17.0.10
j  java.lang.Thread.run()V+11 java.base@17.0.10
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x000001e646746118

**Comment by bonede** [comment]
`v0.22.6a` has fixed a few memory related issues, please upgrade to this version and try again.

If it still occurs, please paste the test code here.

**Comment by bonede** [comment]
Please upgrade to 0.22.6.1. This should fix the versioning issue.
