### ISSUE TITLE
Is this project adtively maintained?

### ISSUE THREAD

**Issue by jiseongg** [bonede/tree-sitter-ng#4]
I was looking for Java bindings of parser library/framework, and found this repo in [tree-sittter.github.io](https://tree-sitter.github.io/tree-sitter/). The document says there are two Java bindings, one is this repo and the other is https://github.com/serenadeai/java-tree-sitter, which I don't think is not updated frequently.

There are several official language bindings maintained by tree-sitter github organization, such as [python binding](https://github.com/tree-sitter/py-tree-sitter). Is this project independent from them?

Thank you

**Comment by bonede** [comment]
Hi, this project is a third party Java binding for tree sitter, and is actively maintained.

**Comment by jiseongg** [comment]
Thank you for the quick response. 👍 I've just finished setup for my project to use this binding. :)
