### ISSUE TITLE
Support for tree-sitter-hocon

### ISSUE THREAD

**Issue by valepakh** [bonede/tree-sitter-ng#44]
Hello!
I tried to create new parser myself but faced a lot of issues, probably due to the fact that I'm on Windows.
Could you please add new parser from https://github.com/antosha417/tree-sitter-hocon?
Thanks!

**Comment by bonede** [comment]
Hi @valepakh , 

Thanks for the contribution. 

I have merge the PR and pushed the package to the maven repo.
