### ISSUE TITLE
Tree Sitter Highlight Support

### ISSUE THREAD

**Issue by nrayburn-tech** [bonede/tree-sitter-ng#5]
Is it possible to support tree sitter highlighting?  https://tree-sitter.github.io/tree-sitter/syntax-highlighting

At a glance, I think this requires bindings for the tree-sitter-highlight library but also some way to load the files such as `highlights.scm` and `tags.scm`.

**Comment by bonede** [comment]
Hi, highlighting will not be supported in near future.It is written in Rust and makes the cross compiling toolchain more complex.
