### ISSUE TITLE
Javadoc is in Chinese

### ISSUE THREAD

**Issue by Marcono1234** [bonede/tree-sitter-ng#52]
**Describe the bug**
The Javadoc `tree-sitter-0.23.0-javadoc.jar` published to Maven Central is in Chinese:
![Javadoc screenshot](https://github.com/user-attachments/assets/63edf579-e427-4626-8d93-4a955d97b9f0)

**Expected behavior**
Since the documentation is in English, the Javadoc should probably be generated in English as well?

You can use the `javadoc` `-locale` argument to explicitly set the Locale to use, see [documentation](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javadoc.html). That should probably fix it.

**Additional context**
A bit related to this: Maybe it would be useful to add a javadoc.io badge and link to the README so users can more easily browse the Javadoc online?

Markdown code:
```md
[![javadoc](https://javadoc.io/badge2/io.github.bonede/tree-sitter/javadoc.svg)](https://javadoc.io/doc/io.github.bonede/tree-sitter) 
```

Rendered:
> [![javadoc](https://javadoc.io/badge2/io.github.bonede/tree-sitter/javadoc.svg)](https://javadoc.io/doc/io.github.bonede/tree-sitter) 

(not completely sure why it still shows "0.22.6.1" as latest version, that will probably fix itself over time?)

**Comment by bonede** [comment]
Great idea!

Planned to fix this in the next release.

**Comment by bonede** [comment]
Hi,

Javadoc was localized  in English in 0.24.3.

**Comment by Marcono1234** [comment]
Thanks! Feel free to close this issue if you think this is resolved.
