### ISSUE TITLE
Update tree-sitter grammars to newest version

### ISSUE THREAD

**Issue by brookite** [bonede/tree-sitter-ng#58]
Many official tree-sitter grammar repositories have already updated to newest versions, for example Python, Java, C++ grammars (https://github.com/tree-sitter/tree-sitter-cpp/releases/tag/v0.23.4). But tree-sitter-ng java grammar bindings haven't been updated since April or May 2024. Will they be updated? New versions may contain improvements

**Comment by brookite** [comment]
Oops, accidentally set the bug label Please remove it

**Comment by bonede** [comment]
Hi,

Thanks for reminding me. I've upgraded a couple of parsers to the latest version.
